export const categoryImages = {
    'automotive': require('../../assets/categories/automotive.jpg'),
    'fragrances': require('../../assets/categories/fragrances.jpg'),
    'furniture': require('../../assets/categories/furniture.jpg'),
    'groceries': require('../../assets/categories/groceries.jpg'),
    'home-decoration': require('../../assets/categories/home-decoration.jpg'),
    'laptops': require('../../assets/categories/laptops.jpg'),
    'lighting': require('../../assets/categories/lighting.jpg'),
    'mens-shirts': require('../../assets/categories/mens-shirts.jpg'),
    'mens-shoes': require('../../assets/categories/mens-shoes.jpg'),
    'mens-watches': require('../../assets/categories/mens-watches.jpg'),
    'motorcycle': require('../../assets/categories/motorcycle.jpg'),
    'skincare': require('../../assets/categories/skincare.jpg'),
    'smartphones': require('../../assets/categories/smartphones.jpg'),
    'sunglasses': require('../../assets/categories/sunglasses.jpg'),
    'tops': require('../../assets/categories/tops.jpg'),
    'womens-bags': require('../../assets/categories/womens-bags.jpg'),
    'womens-dresses': require('../../assets/categories/womens-dresses.jpg'),
    'womens-jewellery': require('../../assets/categories/womens-jewellery.jpg'),
    'womens-shoes': require('../../assets/categories/womens-shoes.jpg'),
    'womens-watches': require('../../assets/categories/womens-watches.jpg'),
};